openapi: 3.1.0
info:
  title: Upselia Actions Backend
  description: API para acciones de Upselia (MVP)
  version: 1.0.1

servers:
  - url: https://upselia-actions-backend.onrender.com

paths:
  /open_link:
    post:
      operationId: open_link
      summary: Devuelve una URL desde Links_Env.json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url_key:
                  type: string
                  description: Clave definida en links de Links_Env.json
                  example: faqs
              required:
                - url_key
      responses:
        "200":
          description: URL resuelta
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  url_key:
                    type: string
                  url:
                    type: string
                    format: uri

  /open_checkout:
    post:
      operationId: open_checkout
      summary: Devuelve link de checkout (por url_key, trainer o defaults)
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                url_key:
                  type: string
                  example: stripe_default
                trainer:
                  type: string
                  example: sample_trainer
      responses:
        "200":
          description: URL de checkout
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  resolved_key:
                    type: string
                  resolved_from:
                    type: string
                  url:
                    type: string
                    format: uri

  /create_ticket:
    post:
      operationId: create_ticket
      summary: Crear un ticket y devolver ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                topic:
                  type: string
                message:
                  type: string
                trainer:
                  type: string
                extra:
                  type: object
              required:
                - topic
                - message
      responses:
        "200":
          description: Ticket creado
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  ticket_id:
                    type: string
